import Home from './Home'
import About from './About'
import Events from './Events'
import Shop from './Shop'
import Contact from './Contact'
import MobileHome from './MobileHome'
import ProductDetail from './ProductDetail'
import CartModal from './CartModal'
import ShoppingCart from './ShoppingCart'
export { Home, About, Events, Shop, Contact, MobileHome, ProductDetail, CartModal, ShoppingCart }